services:
  database:
    container_name: mysql_compose
    image: mysql:latest
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - ~/cmy/mysql:/var/lib/mysql

